services:
  jenkins-server:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-server
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.jenkins-agent
    container_name: jenkins-agent
    depends_on:
      - jenkins-server
    environment:
      - JENKINS_URL=http://jenkins-server:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      -url http://jenkins-server:8080
      -secret d70d50350b9b5d805f1e037e6a41522c1e5dcbf630fe537cdf11afb7123a2be4
      -name jenkins-agent
      -workDir /home/jenkins/agent

volumes:
  jenkins_home:
